name: Check Apex API Version

on:
    workflow_dispatch:
    schedule:
        - cron: '0 8 * * 1'

jobs:
    check-api-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Authenticate Salesforce
              run: |
                npm ci
                echo '{"sfdxAuthUrl": "${{ secrets.SF_AUTH_URL }}"}' > authFile.json
                npm i -g @salesforce/cli
                sf org login sfdx-url --sfdx-url-file "authFile.json" --set-default-dev-hub --alias DevHub --set-default
            - name: Check API Version
              run: |
                node scripts/typescript/build/check-apex-api-version.js