name: Check API Version

on:
    workflow_dispatch:

jobs:
    check-api-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Authenticate Salesforce
              run: |
                echo '{"sfdxAuthUrl": "${{ secrets.SF_AUTH_URL }}"}' > authFile.json
                npm i -g @salesforce/cli
                sf org login sfdx-url --sfdx-url-file "authFile.json" --set-default-dev-hub --alias DevHub
            - name: Check API Version
              run: |
                node scripts/typescript/build/check-apex-api-version.js