name: CodeScan Pull Request On Main

on:
  pull_request:
    branches:
      - main
      - release
    paths:
      - "**/main/default/**"
    
    
jobs:
  code-scan-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Run Code Scan
        uses: ZackFra/sfdx-codescan@master