name: CodeScan Pull Request On Main

on:
  workflow_call:
    
    
jobs:
  code-scan-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Run Code Scan
        uses: ZackFra/sfdx-codescan@master