name: Deploy
on:
    workflow_call:

env:
  AWS_SECRET: ${{ secrets.AWS_SECRET }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_GET_DEPLOYMENT_FUNC: ${{ secrets.AWS_GET_DEPLOYMENT_FUNC }}
  SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
  REPOSITORY: ${{ github.repository }}
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy-pull-request:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dont deploy') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Auth File
        run: scripts/bash/create-sfdx-auth-file.sh ${{ secrets.SF_AUTH_URL }}
      - name: Get Deployment
        id: get_deployment
        run: scripts/bash/get-deployment.sh
      - uses: ZackFra/sf-delta-deploy@master
        with:
          branch: origin/main
          quick-deploy-id: ${{ steps.get_deployment.outputs.quick-deploy-id }}
