name: Deploy
on:
    push:
      branches:
        - main
      paths:
        - "**/main/default/**"

jobs:
  deploy-pull-request:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy to Prod
        uses: ZackFra/sfdx-deploy@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sfdx-auth-url: ${{ secrets.SFDX_AUTH_URL }}
          base-branch: origin/main
          validate-only: false