name: Deploy
on:
    pull_request_target:
      types: [closed]
      branches:
        - main
      paths:
        - "**/main/default/**"

jobs:
  deploy-pull-request:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dont deploy') && github.event.pull_request.merged == true }}
    steps:
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Auth File
        run: |
          echo '{"sfdxAuthUrl": "${{ secrets.SF_AUTH_URL }}"}' > authFile.json
      - uses: ZackFra/sf-delta-deploy@master
        with:
          branch: origin/main
          quick-deploy-id: ${{ steps.PR.outputs.pr_body }}