name: Deploy
on:
    pull_request_target:
      types: [closed]
      branches:
        - main
      paths:
        - "**/main/default/**"

jobs:
  deploy-pull-request:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dont deploy') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Auth File
        run: scripts/bash/create-sfdx-auth-file.sh
      - name: Get Quick Deploy Id
        run: scripts/bash/get-deployment.sh
      - uses: ZackFra/sf-delta-deploy@master
        with:
          branch: origin/main
          quick-deploy-id: ${{ steps.PR.outputs.PR }})