name: Diagnostic

on:
    workflow_dispatch:

env:
    SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}

jobs:
    run-diagnostics:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Compile Go
              run: make github
            - name: Create Auth File
              run: scripts/bash/create-sfdx-auth-file.sh
            - name: Authenticate DevHub
              run: scripts/bash/config-sf.sh authFile.json
            - name: Run Diagnostics
              run: npm run diagnostics -- instance_upgrade.json