name: Generate Apex Docs

on:
  workflow_call:
  workflow_dispatch:


jobs:
    generate-apex-docs:
        permissions:
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-node@v4
            with:
              node-version: '20'
          - uses: actions/create-github-app-token@v1
            id: app-token
            with:
              app-id: ${{ secrets.APP_ID }}
              private-key: ${{ secrets.APP_SECRET }}
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              token: ${{ steps.app-token.outputs.token }}
          - name: Generate Apexdocs
            run: scripts/bash/generate-apex-docs.sh ${{ github.run_id }} ${{ steps.app-token.outputs.token }} ${{ github.token }}