name: Validate

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/main/default/**"

env:
  AWS_SECRET: ${{ secrets.AWS_SECRET }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SAVE_DEPLOYMENT_FUNC: ${{ secrets.AWS_SAVE_DEPLOYMENT_FUNC }}
  SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
  REPOSITORY: ${{ github.repository }}
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

jobs:
    code-scan:
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'dont deploy') }}
      uses: ./.github/workflows/code-scan.yaml
      secrets: inherit
    check-for-duplicates:
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'dont deploy') }}
      uses: ./.github/workflows/check-for-duplicates.yaml
      secrets: inherit
    verify-prettier:
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'dont deploy') }}
      uses: ./.github/workflows/prettier-check.yaml
      secrets: inherit
    validate-changes:
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'dont deploy') }}
      needs: [code-scan, check-for-duplicates, verify-prettier]
      uses: ./.github/workflows/validate.yaml
      secrets: inherit
    