name: On Pull Request (Apex Changes)

on:
  pull_request:
    branches:
      - main
      - release
    paths:
      - "**/main/default/**"

env:
  AWS_SECRET: ${{ secrets.AWS_SECRET }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SAVE_DEPLOYMENT_FUNC: ${{ secrets.AWS_SAVE_DEPLOYMENT_FUNC }}
  SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
  REPOSITORY: ${{ github.repository }}
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

jobs:
    code-scan:
      permissions:
        contents: write
      uses: ./.github/workflows/code-scan.yaml
      secrets: inherit
    check-for-duplicates:
      permissions:
        contents: write
      uses: ./.github/workflows/check-for-duplicates.yaml
      secrets: inherit
    validate-changes:
      needs: [code-scan, check-for-duplicates]
      uses: ./.github/workflows/validate.yaml
      secrets: inherit
    