name: Publish Unlocked Package

on:
    workflow_call:
    workflow_dispatch:

jobs:
    publish-unlocked-package:
        permissions:
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.APP_SECRET }}
            - name: Checkout
              uses: actions/checkout@v4
              with:
                token: ${{ steps.app-token.outputs.token }}
                fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Create Auth File
              run: scripts/bash/create-sfdx-auth-file.sh ${{ secrets.SF_AUTH_URL }}
            - name: Authenticate DevHub
              run: scripts/bash/config-sf.sh authFile.json
            - name: Publish Package
              run: scripts/bash/publish-unlocked-package.sh ${{ github.run_id }} ${{ steps.app-token.outputs.token }} ${{ github.token }}